name: Build CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        java: [8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: build
        run: mvn -B clean package -DskipTests=true

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            target/*.jar
